/**
 * @see https://discord.com/developers/docs/topics/rpc#commands-and-events-rpc-events
 */
enum PayloadEvent {
    CurrentUserUpdate = 'CURRENT_USER_UPDATE',
    GuildStatus = 'GUILD_STATUS',
    GuildCreate = 'GUILD_CREATE',
    ChannelCreate = 'CHANNEL_CREATE',
    RelationshipUpdate = 'RELATIONSHIP_UPDATE',
    VoiceChannelSelect = 'VOICE_CHANNEL_SELECT',
    VoiceStateCreate = 'VOICE_STATE_CREATE',
    VoiceStateDelete = 'VOICE_STATE_DELETE',
    VoiceStateUpdate = 'VOICE_STATE_UPDATE',
    VoiceSettingsUpdate = 'VOICE_SETTINGS_UPDATE',
    VoiceSettingsUpdate2 = 'VOICE_SETTINGS_UPDATE_2',
    VoiceConnectionStatus = 'VOICE_CONNECTION_STATUS',
    SpeakingStart = 'SPEAKING_START',
    SpeakingStop = 'SPEAKING_STOP',
    GameJoin = 'GAME_JOIN',
    GameSpectate = 'GAME_SPECTATE',
    ActivityJoin = 'ACTIVITY_JOIN',
    ActivityJoinRequest = 'ACTIVITY_JOIN_REQUEST',
    ActivitySpectate = 'ACTIVITY_SPECTATE',
    ActivityInvite = 'ACTIVITY_INVITE',
    NotificationCreate = 'NOTIFICATION_CREATE',
    MessageCreate = 'MESSAGE_CREATE',
    MessageUpdate = 'MESSAGE_UPDATE',
    MessageDelete = 'MESSAGE_DELETE',
    LobbyDelete = 'LOBBY_DELETE',
    LobbyUpdate = 'LOBBY_UPDATE',
    LobbyMemberConnect = 'LOBBY_MEMBER_CONNECT',
    LobbyMemberDisconnect = 'LOBBY_MEMBER_DISCONNECT',
    LobbyMemberUpdate = 'LOBBY_MEMBER_UPDATE',
    LobbyMessage = 'LOBBY_MESSAGE',
    CaptureShortcutChange = 'CAPTURE_SHORTCUT_CHANGE',
    Overlay = 'OVERLAY',
    OverlayUpdate = 'OVERLAY_UPDATE',
    EntitlementCreate = 'ENTITLEMENT_CREATE',
    EntitlementDelete = 'ENTITLEMENT_DELETE',
    UserAchievementUpdate = 'USER_ACHIEVEMENT_UPDATE',
    Ready = 'READY',
    Error = 'ERROR',
}

export default PayloadEvent;
